programs:
  web:
    cmd: "python3 server.py"
    numprocs: 10
    umask: "022"
    autostart: true
    autorestart: false
    exitcodes: [0]
    startretries: 0
    starttime: 10
    stopsignal: TERM
    stoptime: 6
    stdout: hello-web.out
    stderr: hello-web.err
    workingdir: test_programs
    env:
      CONTENT: "hello-web"
      PORT: "8081"

