programs:
  web:
    cmd: "python3 server.py"
    numprocs: 1
    umask: "022"
    autostart: true
    autorestart: false
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: TERM
    stoptime: 6
    stdout: web.out
    stderr: web.err
    workingdir: test_programs

  toto32:
    cmd: echo 1
    numprocs: 1
    umask: "022"
    autostart: true
    autorestart: false
    exitcodes: [0]
    startretries: 0
    starttime: 10
    stopsignal: TERM
    stoptime: 6
    stdout: toto.out
    stderr: toto.err
    workingdir: test_programs
    env:
      CONTENT: "hello-web"
      PORT: "8081"

